version: '3.8'

networks:
  monitor-net:
    driver: bridge

services:
  db:
    image: mysql:8.0
    container_name: wp-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - monitor-net
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp-app
    restart: always
    ports:
      - "8000:80"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_CONFIG_EXTRA=define('WP_REDIS_HOST', 'redis'); define('WP_REDIS_PORT', 6379); define('WP_REDIS_DATABASE', 1);
      - WORDPRESS_DEBUG=1
      - WORDPRESS_DEBUG_DISPLAY=1
    networks:
      - monitor-net
    volumes:
      - wp_data:/var/www/html

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    restart: always
    environment:
      - MYSQLD_EXPORTER_PASSWORD=${MYSQL_PASSWORD}
    command:
      - "--mysqld.username=${MYSQL_EXP_USER}"
      - "--mysqld.address=db:3306"
    networks:
      - monitor-net
    depends_on:
      - db

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    networks:
      - monitor-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports: 
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitor-net
    devices:
      - /dev/kmsg
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - /opt/homelab/config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - /opt/homelab/config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    restart: unless-stopped
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    volumes:
      - /opt/homelab/config/grafana/datasources:/etc/grafana/provisioning/datasources
      - /opt/homelab/config/grafana/dashboards/dashboard_provider.yaml:/etc/grafana/provisioning/dashboards/dashboard_provider.yaml
      - /opt/homelab/config/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - /opt/homelab/grafana/grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki:3.0.0
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitor-net

  promtail:
    image: grafana/promtail:3.0.0
    restart: always
    user: "0:0"
    privileged: true
    volumes:
      - /opt/homelab/config/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitor-net

volumes:
  db_data:
  wp_data:
  grafana_data:

