services:
  jenkins:
    build: .
    container_name: jenkins-ci
    network_mode: host
    user: root
    environment:
      - JENKINS_OPTS=--httpPort=8084
    volumes:
      - jenkins_data:/var/jenkins_home
      - /home/vova/.ssh:/var/jenkins_home/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  vault:
    image: hashicorp/vault:latest
    container_name: vault-server
    network_mode: host
    command: server
    volumes:
      - ./vault-config.hcl:/vault/config/vault-config.hcl:ro
      - vault_storage:/vault/file
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

volumes:
  jenkins_data:
  vault_storage:
