services:
  jenkins:
    build: .
    container_name: jenkins-ci
    network_mode: host
    environment:
      - JENKINS_OPTS=--httpPort=8084
    volumes:
      - jenkins_data:/var/jenkins_home
      - /home/vova/.ssh:/var/jenkins_home/.ssh:ro
    restart: unless-stopped

volumes:
  jenkins_data:
